#person:
#    lastName: zhangsan
#    age: 20
#    boss: false
#    birth: 1995/01/28
#    maps: {k1: v1,k2: v2}
#    lists:
#      - cat
#      - apple
#      - book
#    dog:
#     name: kitty
#     age: 1